let
    Source = Folder.Files("C:\Users\Lydia\Downloads\Art-Class-Storytime-_framedata_per_session"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"response_uuid", type text}, {"child_hashed_id", type text}, {"frame_id", type text}, {"event_number", Int64.Type}, {"key", type text}, {"value", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"event_number", "Source.Name", "response_uuid"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","https://www.science.smith.edu/departments/psych/lquevedo/public_html/img/button_","",Replacer.ReplaceText,{"value"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",".jpg","",Replacer.ReplaceText,{"value"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Value1", "frame_id", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"frame_id.1", "frame_id.2", "frame_id.3"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"frame_id.1", Int64.Type}, {"frame_id.2", type text}, {"frame_id.3", type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([frame_id.2] = "Ask1" or [frame_id.2] = "Ask2" or [frame_id.2] = "Promise1" or [frame_id.2] = "Promise2")),
    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"frame_id.1"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns1", each ([key] = "images.1.id" or [key] = "images.1.src" or [key] = "images.2.id" or [key] = "images.2.src" or [key] = "images.3.id" or [key] = "images.3.src" or [key] = "images.4.id" or [key] = "images.4.src" or [key] = "selectedImage")),
    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows1",".src","",Replacer.ReplaceText,{"key"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",".id","",Replacer.ReplaceText,{"key"}),
    #"Grouped Rows" = Table.Group(#"Replaced Value3", {"child_hashed_id", "frame_id.2", "frame_id.3", "key"}, {{"Count", each Text.Combine([value]), type nullable text}}),
    #"Split Column by Position" = Table.SplitColumn(#"Grouped Rows", "frame_id.3", Splitter.SplitTextByPositions({0, 3}, false), {"frame_id.3.1", "frame_id.3.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Position",{{"frame_id.3.1", type text}, {"frame_id.3.2", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"frame_id.2", "verb"}, {"frame_id.3.1", "wh"}}),
    #"Split Column by Position1" = Table.SplitColumn(#"Renamed Columns", "frame_id.3.2", Splitter.SplitTextByPositions({0, 1}, false), {"frame_id.3.2.1", "frame_id.3.2.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Position1",{{"frame_id.3.2.1", Int64.Type}, {"frame_id.3.2.2", type text}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type3",{{"frame_id.3.2.1", "neg"}, {"frame_id.3.2.2", "type"}}),
    #"Split Column by Position2" = Table.SplitColumn(#"Renamed Columns2", "Count", Splitter.SplitTextByPositions({0, 7}, false), {"Count.1", "Count.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Position2",{{"Count.1", type text}, {"Count.2", type text}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type4",{{"Count.1", "selection"}, {"Count.2", "button"}})
in
    #"Renamed Columns3"